### ISSUE TITLE
jeecg-uniapp跨域问题

### ISSUE THREAD

**Issue by pangole** [jeecgboot/jeecg-uniapp#29]
后端版本：jeecg-boot5.5.4
前端版本：jeecgboot-vue35.5.4
使用docker部署的微服务，前端都是正常的，但是jeecg-uniapp访问就存在跨域问题，请问是需要在后端设置还是需要修改jeecg-uniapp配置

**Comment by zhangdaiscott** [comment]
不太清楚你的配置，另外你的版本号写的很乱
