### ISSUE TITLE
内置浏览器可以登录，链接手机后，无法登录，报如下错误

### ISSUE THREAD

**Issue by tyjohn** [jeecgboot/jeecg-uniapp#3]
![image](https://user-images.githubusercontent.com/3033456/86200734-1d54c180-bb90-11ea-8580-c00f0ce5982f.png)

**Comment by objcat** [comment]
登陆测试过应该没什么问题 你用postman检查一下url地址 项目架构是真的垃圾

**Comment by tyjohn** [comment]
老兄，你觉得项目架构哪有问题，给点建设性意见

谢谢你的回复，我一会检测一下后回复你，我是用的苹果测的



tyjohn@163.com
 
发件人： 不伤手的白猫
发送时间： 2020-07-02 15:58
收件人： zhangdaiscott/jeecg-uniapp
抄送： tyjohn; Author
主题： Re: [zhangdaiscott/jeecg-uniapp] 内置浏览器可以登录，链接手机后，无法登录，报如下错误 (#3)
登陆测试过应该没什么问题 你用postman检查一下url地址 项目架构是真的垃圾

**Comment by jngxx** [comment]
请检查手机WIFI分配的IP与后端是否同一网段
