### ISSUE TITLE
jeecg-uniapp 无法登录

### ISSUE THREAD

**Issue by luwr99** [jeecgboot/jeecg-uniapp#44]
从JeecgBoot官网上下载了uniapp移动端应用。本地用HBuilder X工具直接运行(详见截图)。但是一直无法登录，目前后端应用没有启动，请帮忙看看，谢谢！

![1](https://github.com/user-attachments/assets/e43e790f-9df0-48bb-acb3-ed47d16230b8)

![2](https://github.com/user-attachments/assets/d3ea6f7e-de91-46e8-8c6e-2a3574f11f5c)
![3](https://github.com/user-attachments/assets/d769b503-7454-4c6a-be87-93d8693275d0)

**Comment by luwr99** [comment]
附上点击“登录”时，前台报错日志截图。
![af24c866047b4ff887c418cf7190990a12211212](https://github.com/user-attachments/assets/d5fee599-4d9f-459f-94b5-311f31e8eba1)

**Comment by 7Mike** [comment]
启动后端就能登录了
