### ISSUE TITLE
地图页面在发布到小程序端的时候，苹果打开微信小程序可以正常显示，但是安卓机器打开小程序的时候显示有问题

### ISSUE THREAD

**Issue by origin-zlw** [jeecgboot/jeecg-uniapp#52]
安卓机器打开小程序中的地图的时候，仿佛有一层白布挡着，隐约能看到地图，但是又看不清，然后去搜索了下JEECG小程序，发现在定位那个页面也有这个问题，请问下，这个问题怎么解决

**Comment by zhangdaiscott** [comment]
截图看看

**Comment by origin-zlw** [comment]
不好意思，在issue37中得到解决，没注意看，谢谢回复！
