### ISSUE TITLE
h5地址栏带参数跳转后刷新参数消失

### ISSUE THREAD

**Issue by zjy200719621** [jeecgboot/jeecg-uniapp#6]
h5地址栏带参数跳转后刷新参数消失 比如
http://localhost:8080/page/a?a=1
刷新后
http://localhost:8080/page/a
所有的页面都是如此

**Comment by zjwang1234** [comment]
我也碰到这个问题了，你解决了吗？

**Comment by zjwang1234** [comment]
我通过springboot后台return "abc.html?s=1" 跳转到前台后，?号后面的参数都丢失了

**Comment by cjfan1996** [comment]
有解决方案了没有啊   最近也用到了这个

**Comment by zjd621102** [comment]
router/index.js
encodeURI:true -> encodeURI:false
